micronaut:
  application:
    name: micronaut-kotlin

datasources:
  default:
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
#    schema-generate: CREATE_DROP move to jpa
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'club.geek66.kotlin.micronaut.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop